name: build-and-push-images

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "LICENSE"

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  DOCKER_REPO: "quay.io/willirath/rasmus-cmems-downloads"

jobs:
  build:
    strategy:
      matrix:
        image_purpose: ["motupydownload", "netcdf2zarr"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          CALVER_IMAGE=$DOCKER_REPO:${{ matrix.image_purpose }}-${CALVER}-${SHA7}
          LATEST_IMAGE=$DOCKER_REPO:${{ matrix.image_purpose }}-latest
          echo "CALVER_IMAGE=${CALVER_IMAGE}" >> $GITHUB_ENV
          echo "LATEST_IMAGE=${LATEST_IMAGE}" >> $GITHUB_ENV
          echo "${CALVER_IMAGE}"
          echo "${LATEST_IMAGE}"

      - uses: docker/setup-buildx-action@v1

      - name: Login to quay.io registry
        if: ${{ startsWith(github.ref, 'refs/heads/master')}}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image_purpose }}
          tags: "${{env.LATEST_IMAGE}}, ${{env.CALVER_IMAGE}}"
          push: ${{ startsWith(github.ref, 'refs/heads/master')}}
